### PR TITLE
Skidded gen

### PR DESCRIPTION
**Pull request by discord-trollering**
image - this repo
image
- my repo
This is blatantly copy-pasted from my repo. if you look at the dates

### CODE REVIEW

**Comment by timof121** [comment]
fr

**Comment by femboykissing** [comment]
+

**Comment by discord-trollering** [comment]
discord.gg/arkose-labs for a better & cheaper solving service btw :trollface:

**Comment by january-ca** [comment]
give credits you jew

**Comment by discord-trollering** [comment]
XD

**Comment by femboykissing** [comment]
LOL

**Comment by NxyyLOL** [comment]
ikr

**Pull request closed without merging**
